### ISSUE TITLE
Tests fail on PHP nightly (7.2-dev)

### ISSUE THREAD

**Issue by rxu** [twigphp/Twig#2464]
Early tests against ```- php: nightly``` fail.
1st, the ```length``` filter own Twig's repo test fails (like here https://travis-ci.org/rxu/Twig/jobs/230340700) with error:
```
Twig_Error: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("count(): Parameter must be an array or an object that implements Countable") in "index.twig" at line 7 in "filters/length.test".)
```

2nd, ```include``` tag test fails as well with error:
```
Twig_Error_Syntax: An exception has been thrown during the compilation of a template ("count(): Parameter must be an array or an object that implements Countable") in "include.html".
```
The scenario is: create template file (say, ```include.html```) with the code 
```twig
{% include 'variable.html' %}
```
The ```variable.html``` itself can be either empty or containing some code which is doesn't matter.
Example: https://travis-ci.org/phpbb/phpbb/jobs/231046144#L790
While further debugging the 2nd issue, it turned out that in this scenario, here https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Node/Module.php#L369 the ```$nodes``` consists of 2 elements: ```object(Twig_Node_Expression_Constant)``` and ```NULL```. Performing count on ```NULL``` causes the above PHP 7.2 error.

**Comment by xabbuh** [comment]
see #2462

**Comment by rxu** [comment]
@xabbuh You probably remember I was suggesting the same a while ago here https://github.com/twigphp/Twig/issues/2382 😉 
Nice to see it's going to be fixed right way.

**Comment by fabpot** [comment]
I've merged #2462 and added PHP 7.2 on Travis.

**Comment by rxu** [comment]
Actually, for phpbb we can't move above v.1.26 because of https://github.com/twigphp/Twig/issues/2218, but I'll find a way to test (probably via filter overriding).

**Comment by rxu** [comment]
@fabpot Can't see PHP 7.2 tests for twig though..

**Comment by rxu** [comment]
Also, you forgot to update the non-mbstring fallback part here https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Extension/Core.php#L1364-L1375

**Comment by SpacePossum** [comment]
those can be replaced with `mb_` counterparts as it is polyfilled https://github.com/twigphp/Twig/blob/2.x/composer.json#L31

**Comment by rxu** [comment]
Ok, the length issue seems to be fixed, but the include-related one is still actual.

**Comment by rxu** [comment]
After upgrading to 1.x-dev and fixing the loader, 2nd issue seems to be self-resolved.
Thanks, closing the issue as such.
Waiting for the Twig 7.2-compatible tag 😉
